# Generated by Django 4.0.3 on 2022-03-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vote_text',
            new_name='vote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ans_text',
        ),
    ]
