# Generated by Django 4.0.3 on 2022-03-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiles_location_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_img',
            field=models.ImageField(blank=True, default='profiles/avtar.png', null=True, upload_to='profiles/'),
        ),
    ]
